$schema: "http://json-schema.org/draft-07/schema#"
title: "Silicon Alloy Recipe"
type: object
required:
  - id
  - name
  - steps
properties:
  id:
    type: string
  name:
    type: string
  description:
    type: string
  steps:
    type: array
    items:
      anyOf:
        - type: object
          required: [run]
          properties:
            run:
              anyOf:
                - type: string
                - type: object
                  required: [command]
                  properties:
                    command:
                      type: string
                    args:
                      type: array
                      items:
                        type: string
        - type: object
          required: [wait_for_exit]
          properties:
            wait_for_exit:
              type: boolean
              enum: [true]
        - type: object
          required: [winecfg]
          properties:
            winecfg:
              type: object
              properties:
                version:
                  type: string
        - type: object
          required: [env]
          properties:
            env:
              type: object
              additionalProperties:
                type: string

